name: Create Sphinx website

on:
  # push:
  #   branches:
  #     - main
  #     - website
  pull_request:
    branches:
      - main
      - website

jobs:
  create_website:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write       # Added for GitHub Pages deployment
      id-token: write    # Necessary for actions/deploy-pages
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6

      # Build Doxygen documentation
      # Copied from the act-test.yaml file
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install gcc cmake libopenmpi-dev openmpi-bin  texlive-latex-recommended texlive-latex-extra libxml2 latexmk texlive-fonts-recommended
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda config --add channels conda-forge
          conda install librdkit-dev=2025.09.4 libboost-devel eigen=5.0.1 doxygen graphviz pygments nlohmann_json
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install ACT
        run: |
          cd ${{ github.workspace }}
          mkdir build; cd build
          export MPICXX=/usr/bin/g++
          export MPICC=/usr/bin/gcc
          export CXXFLAGS='-std=c++20'
          cmake -DGMX_DOUBLE=ON -DCMAKE_PREFIX_PATH=/usr/share/miniconda/envs/test -DBUILD_SHARED_LIBS=OFF -DGMX_OPENMP=OFF -DGMX_MPI=ON -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/../tools -DCMAKE_BUILD_TYPE=Release -DACT_BUILD_MANUAL=ON -DCMAKE_CXX_COMPILER=${MPICXX} -DCMAKE_C_COMPILER=${MPICC} ..
          make -j 4 doxygen-full website manual
          mkdir ../_build
          mv docs/html/doxygen/html-full ../_build/doxygen
          mv docs/manual/html/* ../_build/
          mv docs/manual/latex/act.pdf ../_build/
      - name: Upload notebook error log
        if: failure() # Only runs if the job fails
        uses: actions/upload-artifact@v7
        with:
          name: EEM-without-shells-error-log
          path: build/docs/manual/html/reports/jupyter/EEM-without-shells.err.log

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/website') }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

      - name: Install linter
        run: pip install sphinx-lint

      - name: Run linter, will never give an error
        run: sphinx-lint docs || true

